#include "./test_suite_parts.hpp"

namespace c4 {
namespace yml {


constexpr const CasePart_e eIN_________ = CPART_IN_YAML_EVENTS;
constexpr const CasePart_e e___OUT_____ =                      CPART_OUT_YAML_EVENTS;
constexpr const CasePart_e e_______EMIT =                                            CPART_EMIT_YAML_EVENTS;
constexpr const CasePart_e eIN_OUT_____ = CPART_IN_YAML_EVENTS|CPART_OUT_YAML_EVENTS;
constexpr const CasePart_e eIN_____EMIT = CPART_IN_YAML_EVENTS|                      CPART_EMIT_YAML_EVENTS;
constexpr const CasePart_e e___OUT_EMIT =                      CPART_OUT_YAML_EVENTS|CPART_EMIT_YAML_EVENTS;
constexpr const CasePart_e eIN_OUT_EMIT = CPART_IN_YAML_EVENTS|CPART_OUT_YAML_EVENTS|CPART_EMIT_YAML_EVENTS;


// To see the test case contents, refer to this URL:
// https://github.com/yaml/yaml-test-suite/tree/master/test/
constexpr const AllowedFailure allowed_failures[] = {
    // we do not accept container keys
    {"4FJ6", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"6BFJ", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"6PBE", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"KK5P", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"KZN9", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"LX3P", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"M5DY", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"Q9WF", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"SBG9", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"X38W", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    {"XW4D", CPART_ALL, "only string keys allowed (keys cannot be maps or seqs)"},
    // we do not accept anchors with :
    {"2SXE", CPART_IN_YAML|CPART_OUT_YAML, "weird characters in anchors, anchors must not end with :"},
    {"W5VH", CPART_IN_YAML, "weird characters in anchors"},

    // malformed json
    {"35KP", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"6XDY", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"6ZKB", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"7Z25", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"9DXL", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"9KAX", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"JHB9", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"KSS4", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"M7A3", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"RZT7", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"U9NS", CPART_IN_JSON, "malformed JSON from multiple documents"},
    {"W4TN", CPART_IN_JSON, "malformed JSON from multiple documents"},

    // TODO
    {"S4T7", eIN_________, "(false positive) difference in behavior when parsing events"},
    {"U9NS", eIN_________, "(false positive) difference in behavior when parsing events"},
    {"36F6", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"4Q9F", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"4ZYM", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"565N", eIN_________, "need to unescape the newline in the scalar from the events source"},
    {"5BVJ", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"5GBF", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"6SLA", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"6WPF", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"77H8", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"7A4E", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"93WF", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"96L6", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"9TFX", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"A6F9", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"B3HG", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"DWX9", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"F6MC", eIN_____EMIT, "need to unescape the newline in the scalar from the events source"},
    {"F8F9", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"G4RS", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"G992", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"H2RW", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"HMK4", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"HS5T", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"J3BT", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"M29M", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"M9B4", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"MJS9", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"MZX3", eIN_________, "need to unescape the newline in the scalar from the events source"},
    {"NB6Z", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"NP9H", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"PRH3", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"Q8AD", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"R4YG", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"RZT7", eIN_OUT_____, "need to unescape the newline in the scalar the events source"},
    {"T26H", eIN_OUT_EMIT, "need to unescape the newline in the scalar from the events source"},
    {"TL85", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"W42U", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"W4TN", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"XV9V", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"Z67P", eIN_OUT_____, "need to unescape the newline in the scalar from the events source"},
    {"RZP5", CPART_IN_YAML|eIN_OUT_____, "plain scalar block parsing, anchors"},
    {"735Y", CPART_IN_YAML|e___OUT_____, "plain scalar parsing|need to unescape the newline in the scalar from the events source"},
    {"7T8X", CPART_IN_YAML|CPART_OUT_YAML, "scalar block parsing"},
    {"82AN", CPART_IN_YAML, "plain scalar parsing, same indentation on next line is problematic"},
    {"9YRD", CPART_IN_YAML|e___OUT_____, "plain scalar parsing, same indentation on next line is problematic|need to unescape the newline in the scalar from the events source"},
    {"EXG3", CPART_IN_YAML|e___OUT_____, "plain scalar parsing, same indentation on next line is problematic"},
    {"EX5H", CPART_IN_YAML|CPART_EMIT_YAML|e___OUT_____, "plain scalar parsing, same indentation on next line is problematic|need to unescape the newline in the scalar from the events source"},
    {"HS5T", CPART_IN_YAML, "plain scalar parsing, same indentation on next line is problematic"},
    {"35KP", eIN_OUT_____, "scalar 'd e' is wrongly parsed with trailing newline"},
    {"3MYT", eIN_________, "emitting block scalars is not idempotent"},
    {"4CQQ", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"4QFQ", eIN_OUT_EMIT, "emitting block scalars is not idempotent"},
    {"5WE3", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"6HB6", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"6JQW", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"6VJK", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"7TMG", eIN_________, "multiline scalar is parsed wrong"},
    {"7W2P", eIN_________, "multiline scalar is parsed wrong"},
    {"A984", eIN_________, "emitting block scalars is not idempotent"},
    {"AB8U", eIN_________, "emitting block scalars is not idempotent"},
    {"D83L", eIN_________, "block scalars: multiline problems"},
    {"DK3J", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"FP8R", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"JDH8", eIN_________, "emitting block scalars is not idempotent"},
    {"K527", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"KSS4", eIN_________, "emitting block scalars is not idempotent"},
    {"M5C3", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"M7A3", CPART_IN_YAML|e_______EMIT, "emitting block scalars is not idempotent"},
    {"K858", CPART_OUT_YAML|CPART_IN_JSON|eIN_________, "emitting block scalars is not idempotent"},
    {"NAT4", CPART_IN_YAML|CPART_EMIT_YAML|CPART_IN_JSON, "emitting block scalars is not idempotent"},
    {"NJ66", eIN_________, "emitting block scalars is not idempotent"},
    {"P2AD", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"T4YY", eIN_OUT_EMIT, "emitting block scalars is not idempotent"},
    {"T5N4", eIN_OUT_EMIT, "emitting block scalars is not idempotent"},
    {"TS54", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"UT92", eIN_OUT_____, "emitting block scalars is not idempotent"},
    {"XLQ9", eIN_________, "emitting block scalars is not idempotent"},
    {"52DL", eIN_OUT_____, "single ! is parsed as a tag"},
    {"5TYM", eIN_________, "wrong parse result from tags"},
    {"6CK3", eIN_________, "wrong parse result from tags"},
    {"6WLZ", eIN_OUT_EMIT, "single ! is parsed as a tag"},
    {"7FWL", eIN_OUT_____, "tags are parsed wrong"},
    {"8MK2", eIN_________, "tags are parsed wrong"},
    {"9WXW", eIN_OUT_____, "tags are inconsistently treated with !"},
    {"C4HZ", eIN_OUT_____, "tags are inconsistently treated with !"},
    {"CC74", eIN_OUT_____, "tags are inconsistently treated with !"},
    {"CUP7", eIN_OUT_____, "tags are inconsistently treated with !"},
    {"EHF6", eIN_________, "emission of tags is not idempotent"},
    {"P76L", eIN_OUT_____, "wrong parse result from tags"},
    {"S4JQ", eIN_OUT_____, "wrong parse result from tags"},
    {"U3C3", eIN_________, "wrong parse result from tags"},
    {"UGM3", eIN_OUT_____, "wrong parse result from tags"},
    {"Z9M4", eIN_OUT_____, "wrong parse result from tags"},
    {"DFF7", eIN_________, "problem with implicit key"},
    {"FH7J", CPART_IN_YAML|CPART_OUT_YAML, "implicit keys"},
    {"FRK4", eIN_________, "implicit key is wrongly parsed"},
    {"V9D5", eIN_________, "null key is wrongly parsed"},
    {"X8DW", eIN_________, "null key is wrongly parsed"},
    {"ZWK4", eIN_________, "null key is wrongly parsed"},
    {"3UYS", CPART_IN_YAML, "no need to escape the slash in \"a\\/b\""},
    {"4ABK", CPART_IN_YAML_EVENTS, "key is wrongly serialized: 'omitted value:'"},
    {"PW8X", CPART_IN_YAML|CPART_OUT_YAML, "anchors with implicit key"},
    {"6BCT", CPART_IN_YAML, "allow tabs after - or :"},
    {"K54U", eIN_________, "problem with tab after ---"},
    {"DC7X", CPART_IN_YAML, "improve handling of tab characters"},
    {"6FWR", CPART_EMIT_YAML|eIN_OUT_____, "fail to parse"},
    {"9MMW", CPART_IN_YAML, "re the json/yaml incompatibility where a space is required after :"},
    {"A2M4", eIN_________, "fails to parse the value sequence, parses as scalar"},
    {"CN3R", CPART_IN_YAML|CPART_OUT_YAML, "anchors + maps nested in seqs"},
    {"G5U8", CPART_ALL, "sequences with -"},
    {"H3Z8", e___OUT_____, "need to unescape the utf8 characters"},
    {"PUW8", eIN_OUT_____, "empty doc must have an empty val"},
    {"RTP8", eIN_________, "empty doc wrongly added at end"},
    {"Q5MG", eIN_________, "'   {}' is wrongly parsed as a val"},
    {"6XDY", eIN_OUT_____, "empty doc does not get an empty value added to it"},
    {"6ZKB", eIN_____EMIT, "document handling"},
    {"9DXL", eIN_____EMIT, "document handling"},
};


cspan<AllowedFailure> g_allowed_failures = allowed_failures;


} // namespace c4
} // namespace yml
