- run: c4core-install ${{matrix.cxx}}
- name: show info
  run: source .github/setenv.sh && c4_show_info

- name: shared64-configure---------------------------------------------------
  run: source .github/setenv.sh && c4_cfg_test shared64
- name: shared64-build
  run: source .github/setenv.sh && c4_build_test shared64
- name: shared64-run
  run: source .github/setenv.sh && c4_run_test shared64
- name: shared64-pack
  run: source .github/setenv.sh && c4_package shared64

- name: static64-configure---------------------------------------------------
  run: source .github/setenv.sh && c4_cfg_test static64
- name: static64-build
  run: source .github/setenv.sh && c4_build_test static64
- name: static64-run
  run: source .github/setenv.sh && c4_run_test static64
- name: static64-pack
  run: source .github/setenv.sh && c4_package static64

- name: static32-configure---------------------------------------------------
  run: source .github/setenv.sh && c4_cfg_test static32
- name: static32-build
  run: source .github/setenv.sh && c4_build_test static32
- name: static32-run
  run: source .github/setenv.sh && c4_run_test static32
- name: static32-pack
  run: source .github/setenv.sh && c4_package static32

- name: shared32-configure---------------------------------------------------
  run: source .github/setenv.sh && c4_cfg_test shared32
- name: shared32-build
  run: source .github/setenv.sh && c4_build_test shared32
- name: shared32-run
  run: source .github/setenv.sh && c4_run_test shared32
- name: shared32-pack
  run: source .github/setenv.sh && c4_package shared32
